services:
    ico.app.extension:
        class: Ico\Bundle\AppBundle\Twig\Extension
        arguments: ["@service_container"] 
        tags:
            - { name: twig.extension }
    ico.form.type.collection_prototype:
        class: Ico\Bundle\AppBundle\Form\Type\CollectionPrototypeType
        arguments: [ '@service_container' ]
        tags:
            - { name: form.type, alias: collection_prototype }
    ico.form.builder_augmenter:
        class: Ico\Bundle\AppBundle\Form\BuilderAugmenter
        arguments: ["@service_container"]
