services:
    ico.parser.services.database_exporter:
        class: Ico\Bundle\ParserBundle\Services\DatabaseExporter
        arguments: [ "@doctrine.orm.entity_manager" ]
    ico.parser.services.xml_database_formater:
        class: Ico\Bundle\ParserBundle\Services\XmlDatabaseFormater