ico_mass_fight:
    resource: "@IcoMassFightBundle/Controller/"
    type:     annotation
    prefix:   /
    
ico_sheet:
    resource: "@IcoSheetBundle/Controller/"
    type:     annotation
    prefix:   /
    
ico_kingmaker:
    resource: "@IcoKingmakerBundle/Controller/"
    type:     annotation
    prefix:   /

ico_parser:
    resource: "@IcoParserBundle/Controller/"
    type:     annotation
    prefix:   /

ico_rules:
    resource: "@IcoRulesBundle/Controller/"
    type:     annotation
    prefix:   /

ico_app:
    resource: "@IcoAppBundle/Controller/"
    type:     annotation
    prefix:   /

ico_user:
    resource: "@IcoUserBundle/Controller/"
    type:     annotation
    prefix:   /

ico_helper:
    resource: "@IcoHelperBundle/Controller/"
    type:     annotation
    prefix:   /    
   
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"