<?php

namespace Ico\Bundle\KingmakerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MapModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapModelRepository extends EntityRepository
{
}
