services:
    ico.form.type.sheet:
        class: Ico\Bundle\SheetBundle\Form\Type\SheetType
        arguments: [ '@service_container' ]
        tags:
            - { name: form.type, alias: sheet }
    ico.form.type.classLevel:
        class: Ico\Bundle\SheetBundle\Form\Type\ClassLevelType
        arguments: [ '@service_container' ]
        tags:
            - { name: form.type, alias: classLevel }