services:
    ico.form.type.sheet:
        class: Ico\Bundle\SheetBundle\Form\Type\SheetType
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: form.type, alias: sheet }
    ico.form.type.classLevel:
        class: Ico\Bundle\SheetBundle\Form\Type\ClassLevelType
        tags:
            - { name: form.type, alias: classLevel }