services:
    ico.form.type.campaign:
        class: Ico\Bundle\KingmakerBundle\Form\Type\CampaignType
        arguments: [ '@service_container' ]
        tags:
            - { name: form.type, alias: campaign }
    ico.kingmaker.map_extension:
        class: Ico\Bundle\KingmakerBundle\Twig\MapExtension
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: twig.extension }