<?php

namespace Ico\Bundle\KingmakerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DotRepository extends EntityRepository
{
}
