<?php

namespace Ico\Bundle\KingmakerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HexRepository extends EntityRepository
{
    public function findCoordinates($x, $y, \Ico\Bundle\KingmakerBundle\Entity\Map $map) {
	   return $this->findOneBy(
		  array(
			 'x' => $x,
			 'y' => $y,
			 'map' => $map
		  )
	   );
    }
}
