<?php

namespace Ico\Bundle\KingmakerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HexRepository extends EntityRepository {

    public function findCoordinates($x, $y, \Ico\Bundle\KingmakerBundle\Entity\Map $map) {
        return $this->findOneBy(
                        array(
                            'x' => $x,
                            'y' => $y,
                            'map' => $map
                        )
        );
    }
    
    public function findAdjacents(\Ico\Bundle\KingmakerBundle\Entity\Hex $hex) {
        $x = $hex->getX();
        $y = $hex->getY();
        
        $adjacents = array();
        if ($x%2 == 0) {
            $adjacents[] = $this->findCoordinates($x-1, $y, $hex->getMap());
            $adjacents[] = $this->findCoordinates($x-1, $y+1, $hex->getMap());
            $adjacents[] = $this->findCoordinates($x, $y+1, $hex->getMap());
            $adjacents[] = $this->findCoordinates($x+1, $y+1, $hex->getMap());
            $adjacents[] = $this->findCoordinates($x+1, $y, $hex->getMap());
            $adjacents[] = $this->findCoordinates($x, $y-1, $hex->getMap());
        } else {
            $adjacents[] = $this->findCoordinates($x-1, $y-1, $hex->getMap());
            $adjacents[] = $this->findCoordinates($x-1, $y, $hex->getMap());
            $adjacents[] = $this->findCoordinates($x, $y+1, $hex->getMap());
            $adjacents[] = $this->findCoordinates($x+1, $y, $hex->getMap());
            $adjacents[] = $this->findCoordinates($x+1, $y-1, $hex->getMap());
            $adjacents[] = $this->findCoordinates($x, $y-1, $hex->getMap());
        }
        
        return $adjacents;
    }

}
