<?php

namespace Ico\Bundle\KingmakerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RealmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealmRepository extends EntityRepository
{
}
