<?php

namespace Ico\Bundle\RulesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlignmentRepository extends EntityRepository
{
}
