<?php

namespace Ico\Bundle\RulesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CharacterClassLevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterClassLevelRepository extends EntityRepository
{
}
