<?php

namespace Ico\Bundle\RulesBundle\Repository;

//use Doctrine\ORM\EntityRepository;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * FeatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeatRepository extends NestedTreeRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('name' => 'ASC'));
    }
    
    /*
     * findRelatives
     * 
     * Getting only descending children and ascending parents from the element
     */
    public function findRelatives(\Ico\Bundle\RulesBundle\Entity\Feat $feat)
    {
	   return $this->childrenHierarchy($feat);
    }
}
