<?php

namespace Ico\Bundle\RulesBundle\Repository;

//use Doctrine\ORM\EntityRepository;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * FeatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeatRepository extends NestedTreeRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('name' => 'ASC'));
    }
    
    /*
     * findRelatives
     * 
     * Getting only descending children and ascending parents from the element
     * 
     * @param	 Feat    $feat	  Base Feat to search for relatives
     * 
     * @return array   All the genealogic tree of the feat (Parents + Children)
     */
    public function findRelatives(\Ico\Bundle\RulesBundle\Entity\Feat $feat)
    {
	   // Getting full path to Feat
	   $path = $this->getPath($feat);
	   // Getting oldest Feat
	   $dean = $path[0];
	   // Getting all tree from oldest Feat
	   $tree = $this->childrenHierarchy($dean, false, array(), true);
	   
	   return $tree;
    }
    
    
}
